### ISSUE TITLE
Login is checking on email instead of username and always fails

### ISSUE THREAD

**Issue by ksamuel** [videntity/django-djmongo#1]

**Comment by aviars** [comment]
i cant reproduce this ???

**Comment by ksamuel** [comment]
Maybe you need to start the project from scratch for it to happen.

I don't recall we fixed it last time, did we ?

**Comment by aviars** [comment]
We didn't fix it. But It doesn't happen on my copy.  You are using  a copy from github or from Git.   I'm going to add you to a project that is an example of everything installed.  Also has the Django-fhir project installed too.  called djmsample.
